[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "VRMViewMeister"
authors = [{name = "ISHII Eiju", email = "lumidina@gmail.com"}]
dynamic = ["version", "description"]
